create table public."Reservations" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  listing_id bigint not null,
  user_id uuid not null,
  check_in date not null,
  check_out date not null,
  guests integer not null,
  total_amount numeric not null,
  status text not null,
  constraint Reservations_pkey primary key (id),
  constraint Reservations_listing_fkey foreign key (listing_id) 
    references public."Listing"(id)
) TABLESPACE pg_default; 